# Generated by Django 4.1.3 on 2022-11-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='login',
            field=models.CharField(error_messages={'blank': 'Login inserido inválido!', 'invalid': 'Login inserido inválido!'}, max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(default='kyc9dCABXHnX4Y', max_length=128),
        ),
    ]
