# Generated by Django 4.1.3 on 2022-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_login_alter_usuarios_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='login',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(blank=True, default='p4hKgQd6v348KY', max_length=128),
        ),
    ]
